# Generated by Django 5.2.2 on 2025-06-09 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.PositiveBigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(blank=True, to='core.categoria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('ticket', 'Ticket numerado'), ('dni', 'Identificación por DNI')], default='ticket', max_length=6)),
                ('estado', models.CharField(choices=[('pend', 'Pendiente'), ('prog', 'En atención'), ('done', 'Finalizado')], default='pend', max_length=4)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('mesa_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mesa')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.persona')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_real', models.TextField()),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('operador', models.ForeignKey(limit_choices_to={'groups__name': 'Operador'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.turno')),
            ],
            options={
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('modo', 'ticket')), fields=('numero', 'fecha'), name='uniq_numero_por_fecha'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pend', 'prog']), ('modo', 'dni')), fields=('persona',), name='uniq_turno_activo_por_persona'),
        ),
    ]
