# Generated by Django - Add LlamadaTurno model only

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlamadaTurno',
            fields=[
                ('id', models.AutoField(db_column='IdLlamadaTurno', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_column='FechaHoraLlamada', db_index=True)),
                ('tipo_llamada', models.CharField(choices=[('LLAMADA', 'Primera Llamada'), ('RELLAMADA', 'Re-llamada')], db_column='TipoLlamada', default='LLAMADA', max_length=20)),
                ('operador', models.ForeignKey(blank=True, db_column='FkIdOperador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas_realizadas', to='core.usuario')),
                ('turno', models.ForeignKey(db_column='FkIdTurno', on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='core.turno')),
            ],
            options={
                'db_table': 'LlamadaTurno',
                'ordering': ['-fecha_hora'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='llamadaturno',
            index=models.Index(fields=['turno', '-fecha_hora'], name='idx_llamada_turno_fecha'),
        ),
        migrations.AddIndex(
            model_name='llamadaturno',
            index=models.Index(fields=['-fecha_hora'], name='idx_llamada_fecha'),
        ),
    ]
