# Generated by Django 5.2.2 on 2025-06-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterField(
            model_name='atencion',
            name='motivo_real',
            field=models.TextField(verbose_name='detalle / motivo final'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Si la lista está vacía, la mesa acepta cualquier categoría.', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='nombre',
            field=models.CharField(help_text='Identificador visible (Mesa 1, Mesa 2, etc.)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='mesa_asignada',
            field=models.ForeignKey(blank=True, help_text='Se completará al asignar la mesa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mesa'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='modo',
            field=models.CharField(choices=[('ticket', 'Ticket numerado'), ('dni', 'Identificación por DNI')], default='ticket', help_text='Define si el turno usa numeración o DNI.', max_length=6),
        ),
        migrations.AlterField(
            model_name='turno',
            name='numero',
            field=models.PositiveIntegerField(blank=True, help_text='Número secuencial (solo para modo Ticket).', null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='persona',
            field=models.ForeignKey(blank=True, help_text='Persona identificada (solo para modo DNI).', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.persona'),
        ),
    ]
